name: Notify Discord on Release

on:
  release:
    types: [published]

jobs:
  discord_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Webhook
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          REPO: ${{ github.repository }}
          TAG: ${{ github.event.release.tag_name }}
          BODY: ${{ github.event.release.body }}
          DOWNLOAD_URL: https://smnsportslive.org/download
          ROLE: "<@&1504903044771479693>"
        run: |
          PAYLOAD=$(jq -n \
            --arg content "**New Release Published!** $ROLE\nRepository: $REPO\nRelease: $TAG\nDescription: $BODY\n[Download Here]($DOWNLOAD_URL)" \
            '{content: $content}')

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$PAYLOAD" \
               "$WEBHOOK_URL"
