name: Notify Discord on Release

on:
  release:
    types: [published]

jobs:
  discord_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Webhook
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "content": "**New Release Published!**\nRepository: '"${GITHUB_REPOSITORY}"'\nRelease: '"${GITHUB_REF#refs/tags/}"'\nDescription: '"${{ github.event.release.body }}"'\n[View Release]('"${{ github.event.release.html_url }}"')"
               }' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
